graphql-hive/gateway

- .changeset/happy-phones-admire.md
- packages/runtime/src/plugins/usePropagateHeaders.ts
- packages/runtime/tests/propagateHeaders.spec.ts
Based on https://github.com/ardatan/graphql-mesh/pull/7822
> Ability to return headers with multiple values from propagateHeaders:fromSubgraphsToClient

- .changeset/@graphql-hive_gateway-71-dependencies.md
- .changeset/@graphql-hive_gateway-runtime-71-dependencies.md
- packages/gateway/package.json
- packages/gateway/src/index.ts
- packages/runtime/package.json
- yarn.lock
Export `HTTPTransport` from the gateway package directly
> Export HTTP transport from the GW package

- .changeset/@graphql-hive_gateway-148-dependencies.md
- .changeset/@graphql-hive_gateway-runtime-148-dependencies.md
- .changeset/@graphql-mesh_fusion-runtime-148-dependencies.md
- .changeset/@graphql-mesh_hmac-upstream-signature-148-dependencies.md
- .changeset/@graphql-mesh_plugin-opentelemetry-148-dependencies.md
- .changeset/@graphql-mesh_plugin-prometheus-148-dependencies.md
- .changeset/@graphql-mesh_transport-common-148-dependencies.md
- .changeset/@graphql-mesh_transport-http-148-dependencies.md
- .changeset/@graphql-mesh_transport-http-callback-148-dependencies.md
- .changeset/@graphql-mesh_transport-ws-148-dependencies.md
- .changeset/breezy-news-rest.md
- .changeset/brown-planets-remember.md
- packages/delegate/src/mergeFields.ts
- packages/delegate/src/types.ts
- packages/fusion-runtime/src/federation/supergraph.ts
- packages/fusion-runtime/src/unifiedGraphManager.ts
- packages/fusion-runtime/src/utils.ts
- packages/fusion-runtime/tests/__snapshots__/runtime.test.ts.snap
- packages/fusion-runtime/tests/runtime.test.ts
- packages/fusion-runtime/tests/utils.ts
- packages/runtime/src/createGatewayRuntime.ts
- packages/runtime/src/plugins/useDelegationPlanDebug.ts
- packages/runtime/src/plugins/useFetchDebug.ts
- packages/runtime/src/plugins/useRequestId.ts
- packages/runtime/src/plugins/useSubgraphExecuteDebug.ts
- packages/runtime/src/plugins/useUpstreamCancel.ts
- packages/stitch/src/createDelegationPlanBuilder.ts
- packages/stitch/src/memoize5of7.ts
- packages/stitch/src/stitchingInfo.ts
- New hooks to get the query plan and the information about response merging
- Also it adds more logging about the query planning and response merging
> New `onDelegationPlan` and `onDelegationStageExecute` hooks, and stringify lazily debug logs

- .changeset/spotty-gifts-trade.md
- e2e/opentelemetry/gateway.config.ts
- e2e/opentelemetry/opentelemetry.e2e.ts
- packages/gateway/rollup.config.js
- packages/plugins/opentelemetry/src/plugin.ts
- packages/plugins/opentelemetry/src/processors.ts
- Fixes issues with gRPC exporter on Node environments
- Adds E2E tests for both gRPC and HTTP exporters
> fix(opentelemetry): grpc exporter

- .changeset/rare-cherries-buy.md
- packages/executors/http/src/createFormDataFromVariables.ts
- packages/federation/src/supergraph.ts
- packages/runtime/src/plugins/useDelegationPlanDebug.ts
- packages/runtime/src/plugins/useFetchDebug.ts
- packages/runtime/src/plugins/useSubgraphExecuteDebug.ts
Bigger results not do not create bigger outputs but instead they are all logged in a single line
> Logger improvements

- .changeset/@graphql-hive_gateway-runtime-208-dependencies.md
- .changeset/@graphql-mesh_fusion-runtime-208-dependencies.md
- .github/workflows/release.yml
- packages/batch-delegate/package.json
- packages/batch-execute/package.json
- packages/delegate/package.json
- packages/executors/graphql-ws/package.json
- packages/executors/http/package.json
- packages/federation/package.json
- packages/fusion-runtime/package.json
- packages/runtime/package.json
- packages/stitch/package.json
- packages/stitching-directives/package.json
- packages/wrap/package.json
- yarn.lock
> Enable Provenance on NPM releases

- packages/plugins/opentelemetry/package.json
- packages/plugins/opentelemetry/src/processors.ts
- yarn.lock
azure monitor / application insights support
> opentelemetry => azure-monitor/application-insights

- .changeset/bright-frogs-float.md
- .changeset/nice-ducks-smash.md
- e2e/interface-additional-resolvers/interface-additional-resolvers.e2e.ts
- e2e/interface-additional-resolvers/mesh.config.ts
- e2e/interface-additional-resolvers/package.json
- e2e/interface-additional-resolvers/services/Test.ts
- packages/fusion-runtime/src/federation/subgraph.ts
- packages/fusion-runtime/src/federation/supergraph.ts
- packages/stitch/src/stitchingInfo.ts
- packages/stitch/src/typeCandidates.ts
- yarn.lock
Handle additional fields on interfaces correctly
> fix: handle `@resolveTo` on interfaces correctly

- .changeset/itchy-nails-rule.md
- packages/gateway/src/servers/bun.ts
- packages/gateway/src/servers/nodeHttp.ts
- packages/gateway/src/servers/types.ts
Closes https://github.com/graphql-hive/gateway/issues/251
> feat(gateway/cli): `requestTimeout` option to configure server request timeout

- .changeset/old-horses-share.md
- .changeset/ten-cougars-look.md
- bench/federation/federation.bench.ts
- internal/e2e/src/tenv.ts
- packages/executors/http/src/createFormDataFromVariables.ts
- packages/executors/http/src/defaultPrintFn.ts
- packages/executors/http/tests/buildHTTPExecutor.test.ts
- packages/executors/http/tests/handleEventStreamResponse.test.ts
- packages/federation/tests/defer-stream.test.ts
- packages/federation/tests/error-handling.test.ts
- packages/federation/tests/fixtures/gateway/supergraph.ts
- packages/federation/tests/subscription.test.ts
- packages/fusion-runtime/src/utils.ts
- packages/runtime/tests/upstreamCancellation.spec.ts
- \`import\` and \`require\` interop in transport import
- Avoid async/await if possible
> Small improvements

- .changeset/mean-guests-occur.md
- packages/delegate/src/index.ts
- packages/delegate/src/isPrototypePollutingKey.ts
- packages/delegate/src/leftOver.ts
- packages/delegate/src/mergeFields.ts
- packages/stitching-directives/src/stitchingDirectivesValidator.ts
- packages/wrap/src/transforms/TransformQuery.ts
- packages/wrap/src/transforms/WrapQuery.ts
Closes https://github.com/graphql-hive/gateway/pull/492
Closes https://github.com/graphql-hive/gateway/pull/491
Closes https://github.com/graphql-hive/gateway/pull/490
Closes https://github.com/graphql-hive/gateway/pull/489
Closes https://github.com/graphql-hive/gateway/pull/488
Closes https://github.com/graphql-hive/gateway/pull/487
Closes https://github.com/graphql-hive/gateway/pull/486
> Fixes code scanning warnings

- .changeset/mean-guests-occur.md
- packages/wrap/src/transforms/TransformQuery.ts
- packages/wrap/src/transforms/WrapQuery.ts
Applies suggestions from https://github.com/graphql-hive/gateway/pull/506/files#r1927085508
> Extend the changeset for #506

- .changeset/tiny-rivers-build.md
- packages/federation/src/supergraph.ts
- packages/federation/tests/getStitchedSchemaFromLocalSchemas.ts
- packages/federation/tests/optimizations.test.ts
- packages/federation/tests/shared-root.test.ts
Closes #551, closes #465
Ref GW-40
> fix(federation): handle shared root fields

- packages/gateway/rollup.config.js
- packages/gateway/scripts/install-sea-packed-deps.cjs
> Bundle only what's necessary and explain

- .changeset/@graphql-hive_gateway-634-dependencies.md
- .changeset/fifty-olives-explain.md
- .changeset/two-tools-look.md
- packages/gateway/package.json
- packages/gateway/src/cli.ts
- packages/gateway/src/config.ts
- packages/gateway/src/index.ts
- yarn.lock
Related https://github.com/graphql-hive/gateway/issues/576
> New Cache Storage: Upstash Redis

- .changeset/itchy-cherries-behave.md
- .changeset/tasty-actors-marry.md
- e2e/demand-control/demand-control.e2e.ts
- e2e/demand-control/gateway.config.ts
- e2e/demand-control/package.json
- e2e/demand-control/services/books.ts
- packages/runtime/src/createGatewayRuntime.ts
- packages/runtime/src/fetchers/graphos.ts
- packages/runtime/src/plugins/demand-control/calculateCost.ts
- packages/runtime/src/plugins/useDemandControl.ts
- packages/runtime/src/types.ts
- packages/runtime/tests/demand-control.test.ts
- yarn.lock
Docs PR https://github.com/graphql-hive/console/pull/6567
Ref GW-220
> feat: Demand Control (including `@cost` and `@listSize` directives)

- yarn.lock
Fixes https://github.com/graphql-hive/gateway/security/dependabot/29
> Bump axios to fix alert #29

- .github/workflows/release.yml
> Fix examples workflow to run on main branch

- .changeset/angry-countries-act.md
- packages/runtime/src/types.ts
> fix: type of `contentEncoding` option

- .changeset/strange-steaks-flow.md
- .changeset/tidy-yaks-trade.md
- docker-bake.hcl
- e2e/openapi-javascript-wiki/gateway_bun.Dockerfile
- e2e/operation-field-permissions/gateway_bun.Dockerfile
- packages/fusion-runtime/src/utils.ts
- packages/gateway/bun.Dockerfile
- packages/gateway/bun_e2e.Dockerfile
- packages/gateway/node.Dockerfile
- packages/gateway/node_e2e.Dockerfile
- packages/gateway/rollup.config.js
- packages/importer/src/hooks.ts
Ref GW-248
Also change the e2e tests to simulate this behaviour making sure it's tested and works.
> Allow importing user installed modules from the root gateway

- .changeset/brave-squids-chew.md
- .changeset/great-rules-hang.md
- .changeset/stupid-suns-mate.md
- packages/nestjs/src/index.ts
- packages/nestjs/tests/nestjs.test.ts
Ref GW-261, ref GW-260, ref GW-258
> Correct Nest driver type defs and usage of builtin plugins and cache, and avoid creating multiple gateway instances

- .changeset/spotty-goats-search.md
- .changeset/violet-islands-heal.md
- internal/testing/package.json
- internal/testing/src/graphql.ts
- internal/testing/src/index.ts
- packages/runtime/src/getReportingPlugin.ts
- packages/runtime/src/plugins/useHiveConsole.ts
- packages/runtime/tests/hive.spec.ts
- yarn.lock
> Hive reporting usage clientInfo can be an object

- .changeset/angry-goats-divide.md
- packages/stitch/src/getFieldsNotInSubschema.ts
- packages/stitch/tests/stitchSchemas.test.ts
> fix(stitch): extract unavailable fields for a target subschema from the fragments

- .changeset/tiny-files-applaud.md
- .github/workflows/memtest.yml
- .github/workflows/test.yml
- packages/executors/http/src/index.ts
- packages/runtime/tests/subgraph-down.test.ts
Fixes https://github.com/graphql-hive/gateway/pull/177#issuecomment-2751521475
> fix(executor-http): handle empty response with HTTP error

- .changeset/@graphql-mesh_plugin-opentelemetry-957-dependencies.md
- .changeset/tiny-monkeys-bake.md
- packages/plugins/opentelemetry/package.json
- packages/plugins/opentelemetry/src/processors.ts
- yarn.lock
> feat(opentelemetry): remove Azure exporter

- .changeset/twenty-fans-share.md
- packages/delegate/src/leftOver.ts
> enhance(delegate): avoid the global `PromiseWithResolvers`

- .changeset/nervous-carrots-allow.md
- packages/plugins/opentelemetry/src/processors.ts
> feat(opentelemetry): Exporters config is optional

- .changeset/@graphql-hive_gateway-1083-dependencies.md
- .changeset/silent-melons-hunt.md
- e2e/polling/polling.e2e.ts
- e2e/supergraph-file-watcher/mesh.config.ts
- e2e/supergraph-file-watcher/package.json
- e2e/supergraph-file-watcher/services/a.ts
- e2e/supergraph-file-watcher/services/b.ts
- e2e/supergraph-file-watcher/supergraph-file-watcher.e2e.ts
- internal/e2e/src/tenv.ts
- packages/gateway/package.json
- packages/gateway/rollup.config.binary.js
- packages/gateway/rollup.config.js
- packages/gateway/src/commands/handleFork.ts
- packages/gateway/src/commands/supergraph.ts
- yarn.lock
> Support watching supergraph file out-of-box

- .changeset/fifty-houses-march.md
- .changeset/three-gifts-nail.md
- e2e/retry-timeout/gateway.config.ts
- e2e/retry-timeout/mesh.config.ts
- e2e/retry-timeout/retry-timeout.e2e.ts
- e2e/retry-timeout/services/flakey.ts
- e2e/retry-timeout/services/gql-flakey.ts
- e2e/retry-timeout/services/oai-flakey.ts
- e2e/supergraph-file-watcher/supergraph-file-watcher.e2e.ts
- packages/fusion-runtime/src/utils.ts
- packages/plugins/deduplicate-request/src/index.ts
- packages/runtime/src/plugins/useUpstreamRetry.ts
> Provide non-GraphQL upstream service responses to the retry mechanism configuration

- .changeset/large-cats-roll.md
- .github/workflows/test.yml
- packages/gateway/bun.Dockerfile
- packages/gateway/node.Dockerfile
Closes https://github.com/graphql-hive/console/pull/6807
Ref GW-328
> Handle CVEs in Docker image and add security scan to CI

- e2e/federation-subscriptions-passthrough/federation-subscriptions-passthrough.memtest.ts
- internal/perf/src/memtest.ts
Continuation of #1294 realising that more memtests have this issue.
> Expected heavy frame in whatwg-node wrapping

- .changeset/lucky-chicken-confess.md
- packages/runtime/package.json
- packages/runtime/src/createGatewayRuntime.ts
- packages/runtime/tests/subgraph.test.ts
- yarn.lock
> Use the merge resolver for delegated subgraph schemas

- .github/dependabot.yml
- .github/workflows/memtest.yml
- .github/workflows/test.yml
And prevent dependabot from [reverting it](https://github.com/graphql-hive/gateway/pull/1249).
> Use fixed docker-cache action

- packages/plugins/prometheus/grafana.json
Closes https://github.com/graphql-hive/gateway/issues/1072
> fix(grafana.json): Change title from 'Mesh' to 'Hive Gateway'

- yarn.lock
Fixes https://github.com/graphql-hive/gateway/security/dependabot/183
even if it is just dev dependency
> Bump axios to fix security vuln alert
