.changeset/curly-socks-retire.md
package.json
packages/gateway/src/index.ts
yarn.lock

This does not work
```ts
import { useRateLimit } from '@graphql-hive/gateway';
```
Make `useRateLimit` exposed

Make useRateLimit and usePrometheus available from @graphql-hive/gateway

---

.changeset/empty-mangos-kick.md
packages/fusion-runtime/src/federation/subgraph.ts
packages/fusion-runtime/tests/runtime.test.ts

When an existing Federation subgraph is extended by Mesh with extra type merging configuration, respect both configurations instead of overriding existing Federation annotations completely.

fix(fusion-runtime) do not override existing merge config

---

.changeset/mighty-doors-guess.md
packages/gateway/src/index.ts
packages/runtime/src/index.ts

Previously users have to first find out @graphql-mesh/utils is where the logging LogLevel comes from, then install the lib (if using strict deps) and use the LogLevel export from it.
With this change, users can simply set the LogLevel directly from the gateway without any additional imports or deps.

Re-export LogLevel and DefaultLogger for easier access and logging manipulation

---

.changeset/early-scissors-join.md
packages/runtime/src/plugins/useDelegationPlanDebug.ts
packages/runtime/src/plugins/useFetchDebug.ts
packages/runtime/src/plugins/useSubgraphExecuteDebug.ts
packages/runtime/src/utils.ts

Importing `crypto` from `@whatwg-node/fetch` adds a bunch of Node dependencies into the bundle.
Since we dont need true/secure randomness at location where we generate UUIDs, using Math as and RNG is ok.

Generate UUID using Math as RNG keeping platform independency

---

packages/runtime/src/plugins/useDelegationPlanDebug.ts
packages/runtime/src/plugins/useFetchDebug.ts
packages/runtime/src/plugins/useSubgraphExecuteDebug.ts

Aside from the micro perf optimization of stringifying less, it looks better in logs.
👎 
👍

Stringify less and at right positions when debugging subgraphs and fetch

---

.changeset/selfish-poems-allow.md
packages/runtime/src/createGatewayRuntime.ts
packages/runtime/src/types.ts

Support schema extensions in the gateway level, so you can extend the schema with type definitions and resolvers;
```ts
// ...
additionalTypeDefs,
additionalResolvers,
})
```

feat(gateway): support `additionalTypeDefs`

---

.changeset/unlucky-pillows-study.md
packages/batch-execute/src/mergeRequests.ts
packages/batch-execute/tests/batchExecute.test.ts

Fixes  https://github.com/graphql-hive/gateway/issues/225 that batched query generation when optional variables are not prefixed and sent correctly.
See the use case below;
When two batched queries are sent like below;
```graphql
query TestOne($someOptionalVar: String) {
foo(someOptionalArg: $someOptionalVar) {
id
name
}
}
```
```graphql
query TestTwo($someOptionalVar: String) {
foo(someOptionalArg: $someOptionalVar) {
id
name
}
}
```
And then `someOptionalVar` is not prefixed if the value is not sent by the user. The batched queries will be sent as below, then it will cause issues.
```graphql
query TestOneTwo($someOptionalVar: String, $someOptionalVar: String) {
_0_foo: foo(someOptionalArg: $someOptionalVar) {
id
name
}
_1_foo: foo(someOptionalArg: $someOptionalVar) {
id
name
}
}
```

fix(batch-execute): prefix non-provided variables correctly

---

.changeset/slow-cars-mate.md
packages/delegate/src/mergeFields.ts
packages/stitch/tests/mergeFailures.test.ts

Do not forward unnecessary post-execution validation errors to the gateway, stitched schema will already handle post-execution validation of non-nullability etc.

fix(delegate): do not forward non-nullability errors to the gateway

---

.changeset/tall-games-destroy.md
.changeset/thick-files-end.md
packages/fusion-runtime/src/utils.ts

`require` causes rollup to create `createRequire` statement etc.
Just use \`globalThis.require\` if exists

fix(runtime): avoid `require` directly but use `globalThis.require`

---

.changeset/calm-dragons-nail.md
packages/fusion-runtime/package.json
packages/fusion-runtime/scripts/replace-import-with-require.mjs
packages/fusion-runtime/src/utils.ts

Always use \`require\` in CJS builds to avoid confusion between \`import\` and \`require\`.
Environments like Jest etc do not support \`import\` on built CJS files in node_modules.

fix(runtime): use `require` in CJS build

---

.changeset/wise-seahorses-rhyme.md
e2e/apq-subgraphs/apq-subgraphs.e2e.ts
e2e/apq-subgraphs/gateway.config.ts
e2e/apq-subgraphs/mesh.config.ts
e2e/apq-subgraphs/package.json
e2e/apq-subgraphs/services/greetings.ts
internal/e2e/src/tenv.ts
packages/executors/http/package.json
packages/executors/http/src/createFormDataFromVariables.ts
packages/executors/http/src/index.ts
packages/executors/http/src/prepareGETUrl.ts
packages/executors/http/src/utils.ts
packages/executors/http/tests/apq.test.ts
packages/transports/http/src/index.ts
yarn.lock

Closes #272 
Automatic Persisted Queries support for upstream requests
For HTTP Executor;
```ts
buildHTTPExecutor({
// ...
apq: true,
})
```
For Gateway Configuration;
```ts
transportEntries: {
'*': {
options: {
apq: true
}
}
},
})
```

feat: APQ between subgraph and gateway

---

.changeset/gorgeous-bananas-brake.md
packages/runtime/src/createGatewayRuntime.ts

Better and less confusing messages on debug logs of readiness check endpoint;
Before;
On successful readiness check, the gateway was logging the following message:
```
Readiness check passed: Supergraph loaded
```
Because this makes the users think it was just loaded.
After;
On successful readiness check, the gateway will log the following message:
```
Readiness check passed because supergraph has been loaded already
```
On failed readiness check, the gateway was logging the following message:
Before;
```
Readiness check failed: Supergraph not loaded
```
It should make the users think it was not loaded or there is an issue with the supergraph.
After;
```
Readiness check failed because supergraph has not been loaded yet or failed to load
```

enhance: better debug messages for readiness check endpoint

---

.changeset/forty-timers-fly.md
e2e/supergraph-url/supergraph-url.e2e.ts
packages/fusion-runtime/src/unifiedGraphManager.ts
packages/fusion-runtime/src/utils.ts
packages/gateway/src/cli.ts
packages/gateway/src/commands/supergraph.ts
packages/runtime/src/createGatewayRuntime.ts

Fix the bug on setting the default polling interval to 10 seconds
So by default, the gateway will poll the schema every 10 seconds, and update the schema if it has changed.
This PR also contains improvements on logging about polling

fix: setting the default polling interval correctly

---

.changeset/calm-eels-hope.md
e2e/retry-timeout/gateway.config.ts
e2e/retry-timeout/package.json
e2e/retry-timeout/retry-timeout.e2e.ts
e2e/retry-timeout/services/flakey.ts
packages/executors/http/src/index.ts
packages/executors/http/src/utils.ts
packages/fusion-runtime/src/utils.ts
packages/runtime/src/plugins/useUpstreamRetry.ts
packages/runtime/src/plugins/useUpstreamTimeout.ts
packages/runtime/tests/upstream-retry.test.ts
packages/transports/common/src/types.ts
yarn.lock

Related https://github.com/graphql-hive/console/pull/6119#issuecomment-2554169308

Add E2E test for Retry/Timeout and some fixes

---

internal/e2e/src/tenv.ts

The `protocol` property does not belong in the `ProcOptions`; even though it's less code - e2e processes dont care about networking (servers do). Also helps with the incoming refactor in #379.
Additionally rename `ServeOptions` to `GatwayOptions`.

E2E processes dont know about networking and rename ServeOptions to GatewayOptions

---

.changeset/nervous-cups-scream.md
packages/batch-delegate/src/getLoader.ts
packages/batch-delegate/tests/basic.example.test.ts
packages/batch-delegate/tests/cacheByArguments.test.ts

Originally fixed by @maxbol in the PR https://github.com/ardatan/graphql-tools/pull/5189
Closes [ #5188](https://github.com/ardatan/graphql-tools/issues/5188)
Fixes [#5189](https://github.com/ardatan/graphql-tools/pull/5189)

fix: batch delegation collapses two requests with different arguments into a single memoized loader

---

.changeset/smart-wasps-smile.md
packages/federation/src/supergraph.ts
packages/federation/tests/shared-root.test.ts

In case of shared root field on Mutation, it was batched incorrectly across subgraphs. But instead only one mutation should be called as mutations should not be parallel

fix(federation): shared mutation field should not be batched

---

.changeset/@graphql-hive_gateway-abort-signal-any-401-dependencies.md
packages/abort-signal-any/package.json
yarn.lock

Update peer dependencies of abort signal any package which is needed because it uses utils as a dependency
Fixes #399

Update peer dependencies of abort signal any package

---

.changeset/wicked-islands-march.md
packages/batch-delegate/src/batchDelegateToSchema.ts
packages/batch-delegate/src/getLoader.ts
packages/batch-delegate/tests/basic.example.test.ts
packages/batch-delegate/tests/cacheByArguments.test.ts

Fixes the regression introduced in https://github.com/graphql-hive/gateway/pull/382
And breaks tests here https://github.com/ardatan/graphql-mesh/pull/8213
This pr fixes the memoization/caching the key arguments correctly;
With the following schema and resolvers, `userById` should batch all the requests to `usersByIds`;
```ts
{
typeDefs: /* GraphQL */ `
type User {
id: ID!
email: String!
}
type Query {
userById(id: ID!): User
usersByIds(ids: [ID!]): [User]
}
`,
resolvers: {
Query: {
usersByIds: (_root, args) => {
return args.ids.map((id: string) => users.find((user) => user.id === id));
},
userById: (root, args, context, info) => {
return batchDelegateToSchema({
schema: userSubschema,
fieldName: 'usersByIds',
key: args.id,
rootValue: root,
context,
info,
})
},
},
},
}
```
This query …

fix(batch-delegate): memoize the key arguments correctly

---

examples/federation-mixed/package-lock.json
examples/federation-mixed/package.json
examples/federation-subscriptions-passthrough/package-lock.json
examples/federation-subscriptions-passthrough/package.json
internal/examples/src/convert.ts
internal/examples/src/utils.ts

- Hide root node_modules when testing making sure examples have all dependencies
- Hide root tsconfig.json when testing making sure compose and gateway configs work
- Actually move devDependencies to dependencies instead of overwriting them

Improvements and bugfixes for examples tester

---

.changeset/heavy-ducks-worry.md
.changeset/real-bulldogs-work.md
.github/workflows/release.yml
packages/federation/src/supergraph.ts
packages/federation/tests/shared-root.test.ts
packages/stitch/src/createDelegationPlanBuilder.ts

In case of shared Mutation field in different subgraphs, choose the best option instead of choosing the last option just like we do in Query root fields

fix(federation): choose the best mutation root field, not take the last available one

---

.changeset/tender-queens-wait.md
e2e/naming-convention-additional-typedefs/__snapshots__/naming-convention-additional-typedefs.e2e.ts.snap
e2e/naming-convention-additional-typedefs/mesh.config.ts
e2e/naming-convention-additional-typedefs/naming-convention-additional-typedefs.e2e.ts
e2e/naming-convention-additional-typedefs/package.json
e2e/naming-convention-additional-typedefs/services/authors.ts
e2e/naming-convention-additional-typedefs/services/books.ts
e2e/naming-convention-additional-typedefs/services/data.ts
packages/wrap/src/transforms/RenameObjectFieldArguments.ts
yarn.lock

`RenameObjectFieldArguments` should transform the passed `args` in `delegationContext`.
When a subschema's a root field argument is renamed, the passed arguments should be also transformed;
```graphql
type Query {
book(book_id: ID): [Book]
}
type Book {
id: ID
title: String
}
```
When the subschema above is transformed to;
```graphql
type Query {
book(bookId: ID): [Book]
}
type Book {
id: ID
title: String
}
```
The following call should be transformed;
```ts
delegateToSchema({
schema: {
schema,
transforms: [
new RenameObjectFieldArguments((typeName, fieldName, argName) => {
if (typeName === 'Query' && fieldName === 'book' && argName === 'book_id') {
return 'bookId';
}
return argName;
})
]
},
operation: 'query',
fieldName: 'book',
args: {
bookId: '1'
}
})
```
To this query;
```graphql
{ …
```

fix(wrap/RenameObjectFieldArguments): transform `args` given in delegation parameters

---

.changeset/beige-experts-rule.md
packages/delegate/src/finalizeGatewayRequest.ts
packages/delegate/tests/finalizeGatewayRequest.test.ts

While creating a delegation request for the subschema, an selection set should be spreaded on the union type field correctly.
In case of the following schema;
```graphql
type Query {
foo: Foo
}
union Foo = Bar | Baz
type Bar {
id: ID!
name: String
age: Age
}
type Age {
years: Int
months: Int
}
type Baz {
id: ID!
name: Name
age: Int
}
type Name {
first: String
last: String
}
```
If the operation is generated as following;
```graphql
query {
foo {
id
name
age {
years
months
}
}
}
```
It should be spreaded on the union type field correctly as following;
```graphql
query {
foo {
... on Bar {
id
age {
years
months
}
}
... on Baz {
id
name {
first
last
}
}
}
}
```

fix(delegate): spread on unions

---

examples/apq-subgraphs/.codesandbox/tasks.json
examples/extra-fields/.codesandbox/tasks.json
examples/federation-example/.codesandbox/tasks.json
examples/federation-mixed/.codesandbox/tasks.json
examples/federation-subscriptions-passthrough/.codesandbox/tasks.json
examples/file-upload/.codesandbox/tasks.json
examples/hmac-auth-https/.codesandbox/tasks.json
examples/interface-additional-resolvers/.codesandbox/tasks.json
examples/json-schema-subscriptions/.codesandbox/tasks.json
examples/openapi-arg-rename/.codesandbox/tasks.json
examples/openapi-subscriptions/.codesandbox/tasks.json
examples/operation-field-permissions/.codesandbox/tasks.json
examples/programmatic-batching/.codesandbox/tasks.json
examples/subscriptions-with-transforms/.codesandbox/tasks.json
examples/type-merging-batching/.codesandbox/tasks.json
internal/examples/src/convert.ts

Correct syntax is using `&>` (and not `$>`).

Redirect example services stdout and stderr to a file

---

packages/gateway/src/cli.ts
packages/gateway/src/commands/proxy.ts
packages/gateway/src/commands/subgraph.ts
packages/gateway/src/commands/supergraph.ts

No need for changeset because the CLI argument was already `polling`, and I changed it to use `pollingInterval` as an option as well to align it with the runtime option `pollingInterval`(we have never released this). 
Now that change is reverted, and the runtime value is taken from `--polling` again.
Reverts this; https://github.com/graphql-hive/gateway/commit/df203610ff9ed50adb3c3c82631ecb5324648486#diff-d6cbbbfb5c53370e686cde8de203e1c0922897847f0ce2595b178af2421197aeR259
It fixes the error when having both `--polling` and `--pollingInterval` in the commanderjs configuration

Fix polling interval option

---

.changeset/green-gifts-serve.md
.changeset/tame-crabs-act.md
packages/gateway/src/cli.ts
packages/gateway/src/commands/handleLoggingOption.ts
packages/gateway/src/commands/proxy.ts
packages/gateway/src/commands/subgraph.ts
packages/gateway/src/commands/supergraph.ts
packages/gateway/src/config.ts

Closes https://github.com/graphql-hive/gateway/issues/567

improvement(cli): allow to pass a factory function to `cache` field

---

.changeset/dull-mayflies-allow.md
e2e/polling/gateway.config.ts
packages/gateway/src/cli.ts
packages/gateway/src/commands/proxy.ts
packages/gateway/src/commands/subgraph.ts
packages/gateway/src/commands/supergraph.ts

Fixes https://github.com/graphql-hive/gateway/issues/573
Ref GW-136

fix(cli): override CLI defaults from configuration

---

.changeset/@graphql-mesh_transport-ws-591-dependencies.md
.changeset/twelve-ghosts-smoke.md
.changeset/twenty-brooms-rush.md
packages/executors/graphql-ws/src/index.ts
packages/transports/ws/package.json
packages/transports/ws/src/index.ts
packages/transports/ws/tests/ws.spec.ts
yarn.lock

Fixes the regression introduced in https://github.com/graphql-hive/gateway/pull/481

fix(executor-graphql-ws): respect the given `lazy` and `lazyCloseTimeout` options

---

.changeset/light-badgers-tan.md
packages/fusion-runtime/src/executor.ts
packages/fusion-runtime/src/federation/subgraph.ts
packages/fusion-runtime/src/federation/supergraph.ts
packages/fusion-runtime/src/unifiedGraphManager.ts
packages/fusion-runtime/src/utils.ts
packages/runtime/src/createGatewayRuntime.ts
packages/runtime/src/utils.ts

Isolate Stitching logic so then we can easily replace Stitching with another Supergraph executor

enhance(runtime): prepare for the future supergraph executor

---

.changeset/@graphql-mesh_fusion-runtime-605-dependencies.md
.changeset/chatty-humans-collect.md
packages/fusion-runtime/package.json
packages/fusion-runtime/src/federation/supergraph.ts
packages/fusion-runtime/src/unifiedGraphManager.ts
packages/fusion-runtime/src/utils.ts
yarn.lock

Batching is now handled by the Gateway not Stitching so a future supergraph executor doesn't need to handle this on its own

refactor(runtime): move subgraph execution batching out

---

.changeset/wild-balloons-repair.md
packages/fusion-runtime/src/utils.ts
packages/logger-winston/package.json
packages/logger-winston/src/index.ts
packages/logger-winston/tests/winston.spec.ts
packages/runtime/src/plugins/useFetchDebug.ts
packages/runtime/src/plugins/useSubgraphExecuteDebug.ts
tsconfig.json
yarn.lock

**Winston Adapter**
Now you can integrate [Winston](https://github.com/winstonjs/winston) into Hive Gateway on Node.js
```ts
import { createLogger, format, transports } from 'winston'
import { createLoggerFromWinston } from '@graphql-hive/winston'
// Create a Winston logger
const winstonLogger = createLogger({
level: 'info',
format: format.combine(
format.timestamp(),
format.json()
),
transports: [
new transports.Console()
]
})
// Create an adapter for Winston
logging: createLoggerFromWinston(winstonLogger)
})
```
In order to try it now, install the alpha of `@graphql-hive/gateway` and `@graphql-hive/winston` below; https://github.com/graphql-hive/gateway/pull/622#issuecomment-2648428148
Related GW-163

Winston Logger Adapter

---

e2e/cloudflare-workers/package.json
package.json
yarn.lock

Fixes https://github.com/graphql-hive/gateway/security/dependabot/25
cookie@^0.5.0 is used by `wrangler` and we don't have a direct dependency affected by runtime.
So this PR forces to install the fixes this alert
Completes GW-185

Fix Vulnerability Alert coming from a dev dependency

---

.changeset/quiet-rules-hunt.md
packages/runtime/src/getReportingPlugin.ts
packages/runtime/src/types.ts

Expose `agentVersion`, `clientName` and `clientVersion` options for GraphOS reporting
And set `hive-gateway@VERSION` by default for `agentVersion`
Fixes https://github.com/graphql-hive/gateway/issues/655
Completes GW-186

feat(runtime/GraphOS): expose `agentVersion`, `clientName` and `clientVersion` options

---

.changeset/fair-mugs-tap.md
packages/delegate/src/mergeFields.ts
packages/stitching-directives/tests/reproductions.test.ts

Fixes https://github.com/ardatan/graphql-tools/issues/6939
When a field with `@skip` and `@include` directives in a selection set throws, show the correct error
```
// Query
query myQuery($toInclude: Boolean! = false) {
user(id: 1) {
id
name
username
totalReviews @include(if: $toInclude) 
}
}
// Variables
{
"toInclude": true
}
```

fix(delegate): handle when a field marked with `@skip` and `@include` throws

---

.changeset/tame-bulldogs-march.md
packages/runtime/src/createGatewayRuntime.ts

Log Fetch calls, subgraph execution and delegation plan generation after all other plugins are invoked
Previously the modification to HTTP headers with header propagation plugin was never seen in debug logs because debug plugins were invoked before all other plugins.

enhance(runtime/debug/log): log debug info after all other plugins are invoked

---

.changeset/@graphql-hive_gateway-runtime-695-dependencies.md
.changeset/@graphql-mesh_plugin-prometheus-695-dependencies.md
packages/plugins/prometheus/package.json
packages/plugins/prometheus/src/index.ts
packages/runtime/package.json
yarn.lock

Related https://github.com/ardatan/whatwg-node/issues/2077

Cleanup unnecessary peer dependencies

---

.changeset/tasty-actors-marry.md
packages/runtime/src/createGatewayRuntime.ts
packages/runtime/src/plugins/useCacheDebug.ts
packages/runtime/src/types.ts
packages/runtime/src/utils.ts

Closes https://github.com/ardatan/graphql-mesh/pull/8355
New Cache related hooks;
`onCacheGet`: invoked when a cache get operation is performed.
`onCacheMiss`: invoked when the performed get operation does not find a cache entry.
`onCacheHit`: invoked when the performed get operation finds a cache entry.
`onCacheGetError`: invoked when an error occurs during a cache get operation.
`onCacheSet`: invoked when a cache set operation is performed.
`onCacheSetDone`: invoked when the performed set operation is completed.
`onCacheSetError`: invoked when an error occurs during a cache set operation.
`onCacheDelete`: invoked when a cache delete operation is performed.
`onCacheDeleteDone`: invoked when the performed delete operation is completed.
`onCacheDeleteError`: invoked when an error occurs …

feat(runtime): new cache related hooks

---

.github/workflows/bench.yml
.github/workflows/memtest.yml

From @enisdenjo here;
> This is right on the edge. The tests run 3x 3min loadtests + 3x 30s calmdown + 10s idling + all of the setup and whatnot.
> 
> Lets do 15mins instead.
https://github.com/graphql-hive/gateway/pull/846#discussion_r1995645765

Increase timeout for mem tests

---

.github/workflows/memtest.yml

Seems like memtests can take even longer than 15mins, lets do 30min x 3.

Increase memtest timeout

---

.github/workflows/release.yml

The old token was update in place and the new one's removed.

Revert "Update release bot token fixing the release process (#853)"

---

.changeset/thick-cars-work.md
e2e/graphos-polling/gateway.config.ts
e2e/graphos-polling/graphos-polling.e2e.ts
packages/plugins/opentelemetry/src/plugin.ts
packages/runtime/src/types.ts
vitest.projects.ts

Do not throw when there is no context in `onFetch` because not all fetch requests happen in GraphQL pipeline
Found while working on GW-232
Still waiting for their confirmation but this was still an issue
Related GW-232

fix(otel): handle outgoing HTTP requests that do not have GraphQL context

---

packages/runtime/tests/subgraph-down.test.ts

Testing subgraph errors in case of nullable and non-nullable field and the inaccesible subgraph

---

packages/runtime/src/createGatewayRuntime.ts
packages/runtime/src/plugins/useHiveConsole.ts
packages/runtime/tests/hive.spec.ts

- Hive Plugin already does disposal;
https://github.com/graphql-hive/console/blob/main/packages/libraries/yoga/src/index.ts#L251
- Hive Plugin sets logger and fetch function
https://github.com/graphql-hive/console/blob/main/packages/libraries/yoga/src/index.ts#L182
- Also pass the fetch implementation to CDN Schema fetcher

Use Hive Yoga plugin itself instead of creating a Hive Client instance

---

.changeset/@graphql-mesh_plugin-opentelemetry-962-dependencies.md
.changeset/pretty-ducks-raise.md
packages/plugins/opentelemetry/package.json
packages/plugins/opentelemetry/src/plugin.ts
yarn.lock

fix(opentelemetry): fix stringified internal errors in logs

---

.changeset/@graphql-hive_gateway-1007-dependencies.md
.changeset/five-kings-sneeze.md
packages/runtime/src/plugins/demand-control/calculateCost.ts
packages/runtime/src/utils.ts
packages/runtime/tests/demand-control.test.ts

Ref GW-271
Fixes https://github.com/graphql-hive/gateway/pull/745/files#r2010264968
Support aliased imports for Demand Control directives such as;
```graphql
extend schema @link(url: "...", import: [{ name: "@cost", as: "@myCost" }])
```
So in this case, `@myCost` will be available in the schema as `@myCost` instead of `@cost`.

fix(runtime): support aliased demand control directive imports

---

.changeset/real-zoos-relate.md
packages/plugins/opentelemetry/src/plugin.ts
packages/plugins/opentelemetry/tests/useOpenTelemetry.spec.ts
packages/plugins/opentelemetry/tests/utils.ts
packages/plugins/opentelemetry/tests/yoga.spec.ts

This PR removes the necessity of passing the HiveGateway logger. This way, the plugin is now usable in Yoga too.
The goal is to improve our subgraphs traces while maintaining only one version of the plugin.
I didn't push the thing up to Envelop only usage, but that's something that should be doable with a bit of effort if we want to.
Related to GW-94

feat(opentelemetry): Allow to use the plugin in Yoga

---

packages/plugins/opentelemetry/src/plugin-utils.ts
packages/plugins/opentelemetry/src/plugin.ts
packages/plugins/opentelemetry/src/spans.ts
packages/plugins/opentelemetry/tests/useOpenTelemetry.spec.ts
packages/plugins/opentelemetry/tests/utils.ts

I didn't found any standard cache related attributes, so I've add custom `gateway.cache` prefix.
I also noticed that the operation name is not set when the result is cached (since the execute hook is not called). I don't want to fix this in this PR because it will involve changes in all response cache plugin variants
Related to GW-168

feat(opentelemetry): add cache events and attributes

---

renovate.json

Because it blocks other packages to be updated. And vitest updates need to be taken care of seperately due to the patches.

Seperate vitest from the renovate group PRs

---

.changeset/cold-monkeys-approve.md
.changeset/giant-paws-battle.md
packages/batch-execute/src/createBatchingExecutor.ts
packages/runtime/src/plugins/useDemandControl.ts
packages/runtime/tests/demand-control.test.ts

Ref GW-300
- If metadata is included the result with `includeExtensionMetadata`, `cost.esTimated` should always be added to the result extensions even if no cost is calculated. So the estimated cost will be 0 in this case. For example `{ __typename }` never hits any subgraph or QP, then it should be 0.
- When multiple root fields are requested from a subgraph(batched execution), and the cost error is thrown as sync then this causes a sync error in DataLoader, and this causes a cryptic error which is masked unexpectedly. In the batching executor, the sync errors are handled and returned in an array that has the same size of the batched requests.

Fixes on Demand Control

---

.changeset/unlucky-ads-itch.md
e2e/federation-batching-plan/federation-batching-plan.e2e.ts
e2e/type-merging-batching/type-merging-batching.e2e.ts
packages/delegate/src/extractUnavailableFields.ts
packages/delegate/tests/extractUnavailableFields.test.ts
packages/federation/src/supergraph.ts
packages/stitch/src/createDelegationPlanBuilder.ts
packages/stitch/src/getFieldsNotInSubschema.ts
packages/stitch/src/stitchingInfo.ts

Ref GW-312
Optimizes `@provides` handling by avoiding the generation of new query plans when a parent subgraph already supplies the requested fields.  
- Refactors and inlines `subtractSelectionSets` to compute leftover selections.  
- Threads a `providedSelectionNode` through planning to subtract out provided fields early.  
- Updates stitching and federation logic to conditionally skip planning when selections are already available.
Note that, this is not a fix for federation compatibility, it is an optimization for the query planner.

Optimize query planner for `@provides`

---

.changeset/@graphql-hive_gateway-runtime-1139-dependencies.md
.changeset/tall-terms-relate.md
packages/runtime/package.json
packages/runtime/src/createGatewayRuntime.ts
packages/runtime/src/types.ts
yarn.lock

Adds `cookies` property to the configuration for cookies processing which is already documented in [here](https://the-guild.dev/graphql/hive/docs/gateway/authorization-authentication#token-lookup)
Ref GW-350

Add missing `cookies` option in the configuration

---

.changeset/smart-islands-hug.md
packages/batch-delegate/src/getLoader.ts
packages/batch-execute/src/createBatchingExecutor.ts
packages/batch-execute/src/splitResult.ts

Micro optimizations on usage of promise helpers and batching
- Avoid extra `handleMaybePromise` call
- Avoid object manipulation and extra `Error` instanceof

enhance(batch): use promise helpers more efficient

---

.changeset/weak-starfishes-begin.md
packages/gateway/node.Dockerfile

This PR is manually upgrading `passwd` because the current version contains a CVE.
This should not be necessary once the upstream image will be updated.
Related to GW-328

fix(gateway): Update docker image to fix CVE related to passwd

---

.changeset/@graphql-hive_gateway-1172-dependencies.md
.changeset/fresh-squids-visit.md
packages/gateway/package.json
packages/gateway/src/cli.ts
yarn.lock

In the CLI package, bundle size is not important so CLI can include the offline bundled version of GraphiQL, while runtime will still use the online version from CDN.
Related feature from the underlying Yoga Server;
https://the-guild.dev/graphql/yoga-server/docs/features/graphiql#offline-usage

enhance(cli): serve graphiql offline by default

---

package.json
yarn.lock

Ref GW-396
In light of https://github.com/advisories/GHSA-g5hg-p3ph-g8qg

Bump multer from 2.0.0 to 2.0.1

---

packages/stitch/README.md

Fixes https://github.com/the-guild-org/website/issues/1802
Was 404.
Now links to correct page.

Docs: Fix stitch link to 404

---

.changeset/big-dolls-invent.md
.changeset/lovely-turtles-sing.md
.changeset/red-teachers-love.md
e2e/header-propagation/gateway.config.ts
e2e/header-propagation/header-propagation.e2e.ts
e2e/header-propagation/services/upstream.ts
package.json
packages/batch-execute/src/mergeRequests.ts
packages/delegate/src/createRequest.ts
packages/delegate/src/delegateToSchema.ts
packages/delegate/src/types.ts
packages/delegate/tests/batchExecution.test.ts
packages/delegate/tests/createRequest.test.ts
packages/fusion-runtime/src/utils.ts
packages/plugins/aws-sigv4/src/plugin.ts
packages/runtime/src/plugins/usePropagateHeaders.ts
packages/runtime/src/plugins/useUpstreamTimeout.ts
packages/wrap/tests/requests.test.ts
yarn.lock

Fixes a bug preventing `subgraphName` to be passed correctly to `fromClientToSubgraphs` when subgraph requests gets batched into a single execution request.
The root cause is more global: the gateway is using a weak map to keep track of the request execution's subgraph name. Which is why it breaks when the execution request is overriden. It was probably also impacting retry logic.
The fix is to move subgraph name directly to the `ExecutionRequest` type. This way, it is easier to track and discover for newcomers.
Related to #1311.

fix(gateway-runtime): Add `subgraphName` to `ExecutionRequest`

---

.changeset/five-pillows-turn.md
e2e/usage-reporting-persisted-operations/gateway.config.ts
e2e/usage-reporting-persisted-operations/package.json
e2e/usage-reporting-persisted-operations/usage-reporting-persisted-operations.e2e.ts
internal/e2e/src/tenv.ts
packages/runtime/src/createGatewayRuntime.ts
packages/runtime/src/types.ts
yarn.lock

Run the persisted documents plugin before the usage reporting and registry plugin

---

.changeset/@graphql-hive_gateway-runtime-1360-dependencies.md
.changeset/@graphql-mesh_plugin-opentelemetry-1360-dependencies.md
.yarn/patches/@opentelemetry-otlp-exporter-base-npm-0.203.0-183dcac0e6.patch
e2e/opentelemetry/opentelemetry.e2e.ts
package.json
packages/plugins/opentelemetry/package.json
packages/plugins/opentelemetry/src/index.ts
packages/plugins/opentelemetry/src/plugin-utils.ts
packages/plugins/opentelemetry/src/plugin.ts
packages/plugins/opentelemetry/tests/useOpenTelemetry.spec.ts
packages/plugins/opentelemetry/tests/utils.ts
packages/plugins/opentelemetry/tests/yoga.spec.ts
packages/runtime/package.json
packages/runtime/src/createGatewayRuntime.ts
packages/runtime/src/types.ts
packages/runtime/src/utils.ts
packages/runtime/tests/graphos.test.ts
yarn.lock

Adds getters to the graphql context and the plugin instance to ease the access to the root spans (http, graphql operation and subgraph executions).
The goal is to allow users to easily modify (like adding custom attributes) to those spans.
There is 3 ways to access those utility functions: 
- via the graphql context (so that it is accessible from the resolvers too).
- via the Gateway Configuration Context, so that Hive plugins can easily have access to it
- via the plugin instance itself, so that other Yoga plugins can easily have access to it
```ts filename="gateway.config.ts"
import './telemetry.ts'
import { defineConfig } from '@graphql-hive/gateway'
import { trace } from '@opentelemetry/api'
openTelemetry: { traces: true },
genericAuth: { …
```

feat(opentelemetry): Add getters for root spans contexts

---

.changeset/rare-chairs-itch.md
packages/stitch/src/mergeCandidates.ts
packages/stitch/tests/mergeOneOfs.test.ts

Fixes https://github.com/graphql-hive/gateway/issues/1404

fix(stitch): handle `@oneOf`s in subschemas

---

.changeset/cute-plums-know.md
.changeset/fine-friends-yawn.md
.changeset/fuzzy-mugs-sit.md
.yarn/patches/@changesets-cli-npm-2.27.9-5df61a909e.patch
.yarn/patches/@changesets-cli-npm-2.29.6-ac8361deb8.patch
package.json
packages/plugins/jwt-auth/src/index.ts
packages/plugins/jwt-auth/tests/auth-directives.spec.ts
packages/plugins/jwt-auth/tests/useJWT.spec.ts
packages/plugins/opentelemetry/src/setup.ts
packages/runtime/src/types.ts
yarn.lock

Seems like the latest changesets does not patch bump internal packages.
No reason not to have it. It's also less work for the user.
```diff
import {
defineConfig,
- Logger
} from "@graphql-hive/gateway";
import { openTelemetrySetup } from "@graphql-hive/gateway/opentelemetry/setup";
- const log = new Logger();
openTelemetrySetup({
- log,
// ...rest
});
- logging: log,
openTelemetry: {
traces: true,
},
});
```
or even
```diff
import {
defineConfig,
- Logger,
} from "@graphql-hive/gateway";
import { openTelemetrySetup } from "@graphql-hive/gateway/opentelemetry/setup";
openTelemetrySetup({
- log: new Logger(),
// ...rest
});
openTelemetry: {
traces: true,
},
});
```
The logs are important though. We …

Create log if not supplied when setting up OTEL, better JWT context inheritance

---

.changeset/clever-cougars-notice.md
.changeset/honest-sheep-remember.md
.github/workflows/test.yml
e2e/graphos-polling/services/gateway-fastify.ts
packages/runtime/src/plugins/usePropagateHeaders.ts
packages/runtime/src/types.ts

And disable windows E2E CI until #1446 lands.

Propagate headers options payloads contain the execution context

---

.changeset/four-books-wash.md
e2e/distributed-subscriptions-webhooks/gateway.config.ts
e2e/event-driven-federated-subscriptions/gateway.config.ts
packages/gateway/src/index.ts

Now it is possible to import `RedisPubSub` and `NATSPubSub` from `@graphql-hive/gateway` package

Export RedisPubSub and NATSPubSub from `@graphql-hive/gateway` package

---

.changeset/weak-zoos-switch.md
e2e/context-log-outside-graphql-execution/context-log-outside-graphql-execution.e2e.ts
e2e/context-log-outside-graphql-execution/gateway.config.ts
e2e/context-log-outside-graphql-execution/package.json
packages/runtime/src/createGatewayRuntime.ts
packages/runtime/src/plugins/useConfigInServerContext.ts
yarn.lock

Inject config context into the server context before all plugins avoiding potential short-circuits

---

.changeset/swift-terms-beam.md
packages/pubsub/tests/pubsub.test.ts
packages/runtime/src/wrapFetchWithHooks.ts
packages/runtime/tests/cache-control.test.ts

The object spread in the code was breaking the reference of the `context` so we can't use WeakMaps or modify the original context object from `onFetch`. It basically copies it which breaks plugins like response-caching;
https://github.com/ardatan/graphql-mesh/actions/runs/17830207715/job/50692979596

fix(runtime): fix the reference of the context passed to `onFetch` hook
